### ISSUE TITLE
Weights not found

### ISSUE THREAD

**Issue by anmolduainter** [IDT-ITI/Lightweight-Face-Detector-Pruning#1]
How to inference it? I am not able to see these weights ?
<img width="883" alt="Screenshot 2024-02-19 at 12 02 35 PM" src="https://github.com/IDT-ITI/Lightweight-Face-Detector-Pruning/assets/26550827/af2a164e-2442-491a-b199-238dcabf2eb9">

**Comment by gkrisp98** [comment]
Hi @anmolduainter ,
to load the models in order to inference them, you need to use this code:

```
net = build_model('train', cfg.NUM_CLASSES, width_mult=0.0625) 
net.load_state_dict(torch.load(path_to_weights))
```
